### PR TITLE
travis does not support windows

### PR DESCRIPTION
**Pull request by tkelman**
you need to enable appveyor for that

### CODE REVIEW

**Comment by DrKrar** [comment]
Dear @tkelman thanks for your interest.
I did not know how such a thing could happen I already run my machine where i am developing this package on windows 10.
I think it may be an issue with "appveyor".

**Comment by tkelman** [comment]
The package manager on Julia nightly uses libgit2 which evidently has problems with tag names that include quotes.

**Comment by DrKrar** [comment]
- the package is running very well on Windows.
- the package is running very well on "juliabox.org" which use Linux.
- it is better to not use quotation inside a package release tag (as i get from your comment).
- I did not know if I should really drop windows from OS in .yamil

**Comment by DrKrar** [comment]
I have tried to validate my .ymal  at "http://lint.travis-ci.org/" and I get a respond that windows is not supported and also julia is illegal !!!!!!.

>    in os section: illegal value windows, defaulting to linux
>    in language section: illegal value julia, defaulting to ruby
>    unexpected key julia, dropping
>    your repository must be feature flagged for the os setting to be used

**Comment by tkelman** [comment]
That linter is apparently using out-of-date information. `language: julia` is "community supported" but it works fine, and multi os testing has not required a feature flag for maybe 6 months

**Comment by DrKrar** [comment]
what I came to is that Windows is not yet supposed but it make no harm to be in the ymail file as it is ignored.
for now i think i will accept the pull request.

**Pull request merged**
